### ISSUE TITLE
Backfill/repair database after changes

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-ethereum#84]
- [x] leaf keys for deleted values: https://github.com/vulcanize/go-ethereum/issues/59
- [x] new logs table: https://github.com/vulcanize/go-ethereum/issues/79
- [x] code and codehash: https://github.com/vulcanize/go-ethereum/issues/90

**Comment by i-norden** [comment]
We aren't going to backfill/repair, instead we are doing a complete sync (https://github.com/vulcanize/ops/issues/76) and will validate using the approach described in https://github.com/vulcanize/ops/issues/78
